### ISSUE TITLE
support code block don't wrap

### ISSUE THREAD

**Issue by zhaihao** [jonas/paradox-material-theme#20]
If one-line code is too long, it will be wrapped, how to disable it?

**Comment by zhaihao** [comment]
```css
.md-typeset pre > code {
    word-break: keep-all;
}
```
I have solved this.
